'use client'
import React, { useState } from 'react';
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import Profiles from "@/utils/profiles/profiles";

const montserrat = Montserrat({ subsets: ["latin"] });

interface Metadata {
  title: string;
  description: string;
}

interface RootLayoutProps {
  children: ReactNode;
}

const metadata: Metadata = {
  title: "Cantina Tech | Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
              {children}
      </body>
    </html>
  );
}
