import { Montserrat } from "next/font/google";
import { ReactNode } from "react";
import '../globals.css'

const montserrat = Montserrat({ subsets: ["latin"] });

interface Metadata {
  title: string;
  description: string;
}

interface RegisterLayoutProps {
  children: ReactNode;
}

const metadata: Metadata = {
  title: "Merendeira | Cadastro",
  description: "Generated by create next app",
};

export default function RegisterLayout({ children }: RegisterLayoutProps) {
  
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
          {children}
      </body>
    </html>
  );
}
